[package]
name = "lightstreamer-rs"
version = "0.1.0"
edition = "2024"
authors = ["Joaquin Bejar <jb@taunais.com>"]
description = "A Rust client for Lightstreamer, designed to facilitate real-time communication with Lightstreamer servers."
license = "MIT"
repository = "https://github.com/joaquinbejar/lightstreamer-rs"
documentation = "https://github.com/joaquinbejar/lightstreamer-rs#readme"


[dependencies]
cookie = { version = "0.18.1", features = ["percent-encode"]}
futures-util = "0.3.31"
json-patch = "4.0.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140" }
serde_urlencoded = "0.7.1"
tokio = { version = "1.45.0", features = ["sync", "macros", "rt-multi-thread"] }
tokio-tungstenite = { version = "0.26.2", features = ["native-tls"] }
tracing = "0.1.40"
url = "2.5.4"
tracing-subscriber = "0.3.19"
